# Oracle/OCI 11g or higher recommended
#
# More info: https://github.com/rsim/oracle-enhanced/
#
# Requires Ruby/OCI8:
#  https://github.com/kubo/ruby-oci8
#
# Specify your database using any valid connection syntax, such as a
# tnsnames.ora service name, or an SQL connect string of the form:
#
#   //host:[port][/service name]
#
# By default prefetch_rows (OCI_ATTR_PREFETCH_ROWS) is set to 100. And
# until true bind variables are supported, cursor_sharing is set by default
# to 'similar'. Both can be changed in the configuration below; the defaults
# are equivalent to specifying:
#
#  prefetch_rows: 100
#  cursor_sharing: similar
#
# Oracle should be read-only from sirsi
oracle_default: &oracle_default
  adapter: oracle_enhanced
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= environment_credential(:oracle_database).squish %>
  username: <%= environment_credential(:oracle_user) %>
  password: <%= environment_credential(:oracle_password) %>


# The Mysql connector is used for any other intermediate data so we dont write to oracle
mysql_default: &mysql_default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

sqlite: &sqlite_default
  adapter: sqlite3
  pool: 5


development:
  <<: *sqlite_default
  database: db/ils_connector_development.sqlite3

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *sqlite_default
  database: db/ils_connector_test.sqlite3

# As with config/secrets.yml, you never want to store sensitive information,
# like your database password, in your source code. If your source code is
# ever seen by anyone, they now have access to your database.
#
# Instead, provide the password as a unix environment variable when you boot
# the app. Read http://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full rundown on how to provide these environment variables in a
# production deployment.
#
# On Heroku and other platform providers, you may have a full connection URL
# available as an environment variable. For example:
#
#   DATABASE_URL="oracle-enhanced://myuser:mypass@localhost/somedatabase"
#
# Note that the adapter name uses a dash instead of an underscore.
#
# You can use this database configuration with:
#
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
#
production:
  <<: *mysql_default
  database: ils_connector_production
  username: ils_connector
  password: <%= ENV['ILS_CONNECTOR_DATABASE_PASSWORD'] %>
